### ISSUE TITLE
tvsp plugin don't build with epgd 1.0.92 git5402395

### ISSUE THREAD

**Issue by FrodoVDR** [chriszero/epgd-plugin-tvsp#1]
g++ -c -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -ggdb -fno-stack-protector -O0 -fPIC -Wextra -Wno-unused-parameter -Wreturn-type -Wall -Wno-parentheses -Wformat -pedantic -Wunused-variable -Wunused-label -Werror=format-security -Wparentheses -Wunused-value -Wunused-function -Wno-long-long -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/mysql -ggdb -fno-stack-protector -O0 -fPIC -Wextra -Wno-unused-parameter -Wreturn-type -Wall -Wno-parentheses -Wformat -pedantic -Wunused-variable -Wunused-label -Werror=format-security -Wparentheses -Wunused-value -Wunused-function -Wno-long-long -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I../.. -Wno-long-long -D_GNU_SOURCE -DBINDEST='"/usr/bin"' -DTARGET='""' -DLOG_PREFIX='""' -DPLGDIR='"/usr/lib/epgd/plugins"' -DUSEUUID -DUSEMD5 -DUSELIBXML -DUSELIBARCHIVE -DUSEJSON -DUSEGUNZIP -I/usr/include/libxml2 -I/usr/include/libxml2 -I/usr/include/python2.7 -I/usr/include/python2.7 -o tvsp.o tvsp.c
tvsp.c: In member function ‘void Tvsp::createXmlNode(json_t*, const char*, xmlNodePtr)’:
tvsp.c:521:54: error: ‘json_array_foreach’ was not declared in this scope
tvsp.c:521:56: error: expected ‘;’ before ‘{’ token
tvsp.c:517:24: warning: unused variable ‘subnode’ [-Wunused-variable]
tvsp.c:520:20: warning: unused variable ‘arraySize’ [-Wunused-variable]
tvsp.c:653:58: error: expected ‘}’ at end of input
tvsp.c:653:58: error: expected ‘}’ at end of input
tvsp.c:500:10: warning: unused variable ‘buffer’ [-Wunused-variable]
tvsp.c:503:17: warning: unused variable ‘strValue’ [-Wunused-variable]
tvsp.c:653:58: error: expected ‘}’ at end of input
make[3]: *** [tvsp.o] Error 1
make[2]: *** [plugins] Error 2

**Comment by chriszero** [comment]
lbijansson is too old.
Use 2.4 or newer.

**Comment by FrodoVDR** [comment]
Thank you, I have installed jansson 2.5 and this fixed this issue.
